name: bone
link: https://cyanophage.github.io/playground.html?layout=jduaxphlmw%C3%9Fctieobnrsgqfv%C3%BC%C3%A4%C3%B6yz%2C.k%27%5E&mode=ergo&lan=german&thumb=l
thumb: false
year: 2014
website: https://www.neo-layout.org/Layouts/bone/
family: ""
