name: but
link: https://cyanophage.github.io/playground.html?layout=bu.%2C%C3%BCpclmfxhieaodtrns%C3%9Fky%C3%B6%C3%A4qjgwvz%27%5E&mode=ergo&lan=german&thumb=l
thumb: false
year: 2010
website: http://www.adnw.de/index.php?n=Main.OptimierungF%C3%BCrDieGeradeTastaturMitDaumen-Shift
family: ""
