name: gallium east
link: https://cyanophage.github.io/playground.html?layout=blcdvjfou%2C-nrstgyheai%2Fqxwmzkp%27%3B.%5C%5E&thumb=l
thumb: false
year: 2026
website: https://www.reddit.com/r/KeyboardLayouts/comments/1rym73o/introducing_galliumeast/
family: "gallium"
