name: handsdown-promethium-inverted-5x3
link: https://cyanophage.github.io/playground.html?layout=vwgmjz.%2C%2F%3B-snthkqaeic-fpdlx%27uoyb%5Cr%5E&thumb=l
thumb: true
year: 2024
website: https://www.reddit.com/r/KeyboardLayouts/comments/1g66ivi/hands_down_promethium_snth_meets_hd_silverengram/
family: "handsdown"
