name: lazyman
link: https://cyanophage.github.io/playground.html?layout=blrdmjfou%2C-nshtgypeia%27qzxcvkw%2F.%3B%5C%5E&thumb=l
thumb: false
year: 2026
website: https://github.com/mohoaz1348-rgb/lazyman
