name: mine
link: https://cyanophage.github.io/playground.html?layout=jluaqwbdgyzcrieomntsh%27vx%C3%BC%C3%A4%C3%B6pf.%2Ck%C3%9F%5E&mode=ergo&thumb=l
thumb: false
year: 2022
website: https://www.neo-layout.org/Layouts/mine/
family: ""
