name: monium_v
link: https://cyanophage.github.io/playground.html?layout=bwhlzqfouy-csrtkxnaei%27gvmdj%3Bp%2C.%2F%5C%5E&thumb=l
thumb: false
year: 2026
website: https://github.com/NotASentientTomato/monium/blob/main/keyboardlayout/README.md
family: "monium"
