name: norden
link: https://cyanophage.github.io/playground.html?layout=qldzkpwou%C3%A4%2Crnthfyceia%3Dxjmbv%27g%C3%B6%C3%BC.%C3%9Fs&mode=ergo&lan=german&thumb=l
thumb: false
year: 0
website: https://discord.com/channels/807843650717483049/1330553325799870526
family: ""
