name: northwest
link: https://cyanophage.github.io/playground.html?layout=blmpw%5Cuoy-%27nrtdf%5Eeaih%2Cxzvcgj%2F%3B.kqs&thumb=l
thumb: true
year: 2026
website: https://rbscholtus.github.io/keycraft/layouts/northwest.html
family: ""
