name: nystyc
link: https://cyanophage.github.io/playground.html?layout=ympgvxquoy-nctsdzriah-wkbf-lj%2C.-%5Ce%5E&thumb=r
thumb: true
year: 2026
website: https://www.reddit.com/r/KeyboardLayouts/comments/1tohq9h/nystyc_my_magnum_opus_of_more_normalish_keyboard/
family: ""
