name: oats
link: https://cyanophage.github.io/playground.html?layout=xydfjzpluq%27oatsgbnrei%3B-%2Cmcvkhw.%2F%5C%5E&mode=ergo&thumb=l
thumb: false
year: 2025
website: https://github.com/rowie324/Oats
family: ""
