name: phoenix
link: https://cyanophage.github.io/playground.html?layout=blrdmyuioj-wnstgphea%3B%27zxcvqkf%2C.%2F%5C%5E&thumb=l
thumb: false
year: 2026
website: https://www.reddit.com/r/KeyboardLayouts/comments/1uq7bzi/phoenix_comfortable_low_pinkie_usage_keyboard/
