name: radial
link: https://cyanophage.github.io/playground.html?layout=xwhmqkpouy%2Fcrnsvgteai-zbflj%3Bd%2C.%27%5C%5E&mode=ergo&thumb=l&lan=english
thumb: false
year: 2026
website: https://github.com/xcambar/radial
