name: snug
link: https://cyanophage.github.io/playground.html?layout=qldmbyfou%27%C3%BCsrtcgpneia%C3%A4zxkwvjh%C3%B6%2C.%C3%9F%5E&mode=ergo&lan=german&thumb=l
thumb: false
year: 2022
website: https://github.com/mndscp/snug-keyboard-layout
family: ""
